### ISSUE TITLE
Deprecation message on Node 0.12 and iojs during upload

### ISSUE THREAD

**Issue by eush77** [jrnewell/simple-http-share#1]
Running on Node 0.12 or iojs, simple-http produces the following deprecation message during file upload:

```
.write(string, encoding, offset, length) is deprecated. Use write(string[, offset[, length]][, encoding]) instead.
```

There is no such message on Node 0.10.

**Comment by jrnewell** [comment]
Fixed in a4aa8db | version `0.1.0`.
